# Generated by Django 4.1.3 on 2022-11-27 09:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listOfName', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rank',
            unique_together={('user', 'rankNumber')},
        ),
    ]
