# Generated by Django 4.1.3 on 2022-11-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listOfName', '0002_alter_rank_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rank',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
